image: gradle:8-jdk17

stages:
  - build
  - run

before_script:
  - apt-get update && apt-get install -y g++

build:
  stage: build
  script:
    - gradle build
  artifacts:
    paths:
      - app/build/exe/main/debug/app
    expire_in: 1 hour

run:
  stage: run
  script:
    - ./app/build/exe/main/debug/app
  dependencies:
    - build
