name: Build and Run

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install C++ build tools
        run: sudo apt-get update && sudo apt-get install -y g++

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build project
        run: ./gradlew build

      - name: Run app
        run: ./app/build/exe/main/debug/app
